# model scale

[General]
coordinate_system = "axisymmetric" # plane_strain or axisymmetric
domain = [[0.0, 0.75], [0.0, 3.1]] # [[xmin, xmax], [ymin, ymax]] (m)
grid_space = 0.005 # (m)
gravity = 9.81     # (m/s2)
total_time = 5.0   # (sec)
output_interval = 0.05 # (sec)
output_folder_name = "output.tmp"
show_progress = true

[[SoilLayer]]
height = 3.0 # (m)
dry_density = 1500.0 # (kg/m3)
poissons_ratio = 0.333
youngs_modulus = 2e6  # (N/m2)
friction_angle = 32.0 # (degree)
dilatancy_angle = 0.0 # (degree)
friction_with_pile = 0.41

[Pile]
diameter_head = 0.15   # (m)
diameter_tip  = 0.15   # (m)
pile_length = 3.0      # (m)
tapered_length = 0.715 # (m)
thickness = 0.01       # (m) NOTE: This must be at least `2 * grid_space`
velocity = 0.4   # (m/s)
vacuum = false
vacuum_height = 0.15 # (m)

[Advanced]
CFL = 0.5
contact_threshold_scale = 1.5
contact_penalty_parameter = 0.0
